

@base=http://127.0.0.1:8080
@username=me

### Get Users DBs
GET {{base}}/dbs/?username={{username}}

### Create DBs
POST {{base}}/dbs
Content-Type: application/json

{
	"username": "{{username}}",
	"dbName": "test_db",
	"dbUser": "test_user",
	"dbPass": "test_pass"
}


