package fresh.crafts.depwiz.enums;

public enum ProjectStatus {

    AWAIT_INITIAL_SETUP,

    PROCESSING_SETUP,
    PROCESSING_DEPLOYMENT,
    PROCESSING_UPDATE,
    PROCESSING_ROLLBACK,
    PROCESSING_ROLLFORWARD,

    PROCESSING_REDEPLOYMENT,
    PROCESSING_DELETION,

    ACTIVE,
    INACTIVE,

}
