package fresh.crafts.engine.v1.utils.enums;

public enum ProjectDeploymentStatus {
    REQUESTED_APPLICATION_SETUP,
    REQUESTED_NGINX_SETUP,
    REQUESTED_SSL_SETUP,

    REQUESTED_APPLICATION_DELETE,
    REQUESTED_NGINX_DELETE,

    PROCESSING_APPLICATION_SETUP,
    PROCESSING_NGINX_SETUP,
    PROCESSING_SSL_SETUP,

    PROCESSING_APPLICATION_DELETE,
    PROCESSING_NGINX_DELETE,

    SUCCESSFUL_DEPLOYMENT,
    FAILED_DEPLOYMENT,
}
