name: FreshCrafts CI/CD

on:
  push:
    branches:
      - main # Modify this to match your branch name
 

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
        group: staging_environment
        cancel-in-progress: true


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "bam!"

            cd freshcrafts
            mv 
            git pull 
            cd bin/
            python3 setup.py 

            echo "tripple bam!"
 